apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "FiapCloudGames"
  Jwt__Audience: "FiapCloudGames"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Username: "guest"
