apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
type: Opaque
stringData:
  ConnectionStrings__Catalog: "Host=postgres;Port=5432;Database=catalog_db;Username=postgres;Password=postgres"
  Jwt__Key: "change-this-secret-key-min-32-chars!!"
  RabbitMQ__Password: "guest"
